### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by tzch96** [tzch96/pk-to#1]
- [ ] fix precedence when parsing functions (sqrt(9)+sqrt(9) should be 6, not ~3.46 which is sqrt(9+sqrt(9)))
- [ ] move functions (for now only sqrt) to plugins folder as a compiled jar
- [ ] dynamically load function plugins at runtime
- [ ] implement design patterns: one from each group creational, structural, behavioral
